CREATE TABLE IF NOT EXISTS contracts (
  id TEXT PRIMARY KEY,
  client_name TEXT,
  client_cpf TEXT,
  client_rg TEXT,
  client_nationality TEXT,
  client_marital_status TEXT,
  client_address TEXT,
  client_city_uf TEXT,
  client_cep TEXT,
  client_phone TEXT,
  client_email TEXT,
  event_type TEXT,
  event_theme TEXT,
  event_date TEXT,
  event_start_time TEXT,
  event_end_time TEXT,
  event_location TEXT,
  included_items TEXT NOT NULL DEFAULT '[]',
  excluded_items TEXT NOT NULL DEFAULT '[]',
  total_value REAL,
  total_value_extenso TEXT,
  down_payment REAL,
  down_payment_percent REAL,
  balance_value REAL,
  balance_due_date TEXT,
  payment_method TEXT,
  down_payment_date TEXT,
  payment_proof_reference TEXT,
  image_authorization INTEGER,
  signature_city TEXT,
  contract_date TEXT,
  observations TEXT,
  generate_attachments INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_contracts_client_name ON contracts(client_name);
CREATE INDEX IF NOT EXISTS idx_contracts_updated_at ON contracts(updated_at);
